### ISSUE TITLE
Binaries for macOS

### ISSUE THREAD

**Issue by nguyenpham** [danieltan1517/orange-xiangqi#4]
Can you please provide:
- binaries for macOS
- a short guide how to compile your programs on various systems

I will make some software tournaments to measure the strength of your Xiangqi engine.

Thanks

**Comment by danieltan1517** [comment]
...yeah...that's going to be a bit of an issue...

I don't have a mac. I could try to get someone else to compile it for mac if you really want a mac version.
This project was written in the "Jai Programming Language", a proprietary programming language in beta, the compiler is not publicly available at all, and only people in the beta (such as myself) can compile the project. If the "Jai Programming Language" is interesting to you, you are free to check out https://github.com/Jai-Community/Jai-Community-Library, and if you are interested, I could try to get one a beta key.

Engine is still quite weak. Still loses to ElephantEye, and definitely gets destroyed by Fairy-Stockfish/Pikafish Xiangqi Engines. Playing strength is around GM level, but still quite weak. Given what I said, in my opinion, it's a waste of time to test it against other engines. I'm in the process of improving it's playing strength.
